# Generated by Django 5.2.5 on 2025-11-08 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número de mesa')),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada')], default='libre', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('en_elaboracion', 'En elaboración'), ('en_cocina', 'En cocina'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='en_elaboracion', max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Enviado a cocina en')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Entregado en')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado en')),
                ('razon_cancelacion', models.TextField(blank=True, null=True, verbose_name='Razón de cancelación')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='mainApp.mesa')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Mesero')),
            ],
        ),
        migrations.CreateModel(
            name='PlatoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='mainApp.pedido')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_items', to='mainApp.plato')),
            ],
        ),
    ]
