# Generated by Django 5.2.8 on 2025-11-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_plato_remove_pedidos_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio'),
        ),
    ]
