# Generated by Django 5.2.8 on 2025-11-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_plato_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='notas_cocina',
            field=models.TextField(blank=True, null=True, verbose_name='Notas para Cocina'),
        ),
    ]
