# Generated by Django 5.2.5 on 2025-11-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_pedidos_notas_cocina'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='stock_consumido',
            field=models.BooleanField(default=False, verbose_name='Stock Consumido en M1'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='stock_validado',
            field=models.BooleanField(default=False, verbose_name='Stock Validado en M1'),
        ),
        migrations.AddField(
            model_name='plato',
            name='plato_id_m1',
            field=models.IntegerField(blank=True, help_text='ID del plato en el módulo de Menú', null=True, verbose_name='ID Plato en M1'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('validando_stock', 'Validando Stock'), ('en_elaboracion', 'En Elaboración'), ('enviado_cocina', 'Enviado a Cocina'), ('listo', 'Listo para Recoger'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
