# Generated by Django 5.2.8 on 2025-11-16 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_pedidos_mesero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Plato')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Plato de Menú',
                'verbose_name_plural': 'Platos de Menú',
            },
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Descuento'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='reserva_stock_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Reserva M1'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='timestamp_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='timestamp_envio_cocina',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Envío a Cocina'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_elaboracion', 'En Elaboración'), ('enviado_cocina', 'Enviado a Cocina'), ('listo', 'Listo para Recoger'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mainApp.pedidos', verbose_name='Pedido')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.plato', verbose_name='Plato')),
            ],
            options={
                'verbose_name': 'Detalle del Pedido',
                'verbose_name_plural': 'Detalles del Pedido',
                'unique_together': {('pedido', 'plato')},
            },
        ),
    ]
